### ISSUE TITLE
Development Server on Windows 7

### ISSUE THREAD

**Issue by JesperDramsch** [ben-bougher/pickr#151]
I am running Win 7 64 bit.
Installed pip and Google App Engine as well as Python27 including numpy, webapp2, jinja2 and PIL.

I started the server with the necessary handles and changed to the master branch with the most recent updates (dev branch isn't up to date yet).

Most of the app is loading, except for the actual content. Uploading to the blob works, but the content is not displayed.

Is there something I'm missing here?

**Comment by kwinkunks** [comment]
Sounds good... Do you mean you can hit 'Upload' and go through the motions, but then you end up back at the 'gallery' view and can't see anything? 

Sounds like you are, but are you definitely logging in as an admin user (check the box on login)? That's the only way you'll be able to upload an image.

Can you look in the console (probably port 8000) to be sure it's actually ending up in the data store?

**Comment by JesperDramsch** [comment]
Yes I am logged in as admin. I checked port 8000 and it arrived in the
blob.

What happened:

+ I hit upload
+ choose file
+ 404 not found
However it is in the blob, but the page doesn't show anything.

By the way is the app supposed to be empty on install?
Am 18.02.2015 02:01 schrieb "Matt Hall" <notifications@github.com>:

**Comment by kwinkunks** [comment]
Ah, sorry, Jesper... so close! 

Yes, it will be empty until you upload something. Since the database should be stable now, you can leave 'clear datastore' UNchecked so you're not constantly uploading things. 

It sounds like it's losing the image_key right away. I wonder if this is related to #94 — any thoughts, @ben-bougher ? I noticed there seems to be duplicate blobs in production the other day. 

I'll call this a bug for now. We'll try to get to it, but none of us are on Windows and we're a bit tied up this week. Meantime, you can try sending some things to the Log window (just print in Python) or the JavaScript console with

    console.log("This piece of text and a variable: " + myVar);

to debug. Firebug for Firefox is super-handy, but all the browsers have good JS inspection now.

**Comment by JesperDramsch** [comment]
Just tried the same on xubuntu, exactly the same error. Are there any packages I'm missing?

**Comment by kwinkunks** [comment]
Hm. Try working in the develop branch. I am wondering if it has to do with the way App Engine handles data — we use Google's cloud storage 'buckets' in production. I don't really know what it does on the dev server, but I live in branch **develop** and leave master to @ben-bougher .

**Comment by JesperDramsch** [comment]
Got it to work on Linux. Windows still not working.

I don't know what made it work on Linux though.

**Comment by kwinkunks** [comment]
OK, well that sounds like a good start. 

For me I think it's more like "I don't know what made it *not* work on Windows" :)

**Comment by JesperDramsch** [comment]
My bet is on some dependency or general gremlins.

**Comment by kwinkunks** [comment]
@JesperDramsch seems to be up and running so I'm closing this because Windows.

**Comment by JesperDramsch** [comment]
I'm developing on Linux, if someone else finds a solution to the Windows-related problems that would be great though.
